version: "3.8"

services: 
  backend.person.api:
    image: backend.person.api
    build: .
    ports:
      - 8080
    deploy:
      replicas: 2
      mode: replicated
      restart_policy: 
        condition: on-failure
    
  