version: "3.8"

services: 
  backend.person.api:
    image: backend.person.api
    build: .
    ports:
      - "8081:8080"
    deploy:
      restart_policy: 
        condition: on-failure
        max_attempts: 3
    networks:
      backend.person.api:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      backend.person.api:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      backend.person.api:

networks:
  backend.person.api:
    driver: bridge